add_library(nav_bmp390 OBJECT bmp390.cpp)
target_include_directories(nav_bmp390 PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_include_directories(nav_bmp390 PRIVATE ${CMAKE_SOURCE_DIR}/include)
target_include_directories(nav_bmp390 PRIVATE ${CMAKE_SOURCE_DIR}/src/02_interfaces/i2c)
target_include_directories(nav_bmp390 PRIVATE ${CMAKE_SOURCE_DIR}/src/03_vendored/BMP3_SensorAPI)
